server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    musicServices: /musics/**
    movieServices: /movies/**
    newServices: /news/**